Ring Buffer: ringbuffer.h File Reference
ringbuffer.h File Reference
#include <inttypes.h>
Data Structures
struct ring_buffer_t
Defines
#define RING_BUFFER_SIZE 128
#define RING_BUFFER_MASK (RING_BUFFER_SIZE-1)
Typedefs
typedef uint8_t ring_buffer_size_t
typedef struct ring_buffer_t ring_buffer_t
Functions
void ring_buffer_init (ring_buffer_t *buffer)
void ring_buffer_queue (ring_buffer_t *buffer, char data)
void ring_buffer_queue_arr (ring_buffer_t *buffer, const char *data, ring_buffer_size_t size)
uint8_t ring_buffer_dequeue (ring_buffer_t *buffer, char *data)
uint8_t ring_buffer_dequeue_arr (ring_buffer_t *buffer, char *data, ring_buffer_size_t len)
uint8_t ring_buffer_peek (ring_buffer_t *buffer, char *data, ring_buffer_size_t index)
uint8_t ring_buffer_is_empty (ring_buffer_t *buffer)
uint8_t ring_buffer_is_full (ring_buffer_t *buffer)
ring_buffer_size_t ring_buffer_num_items (ring_buffer_t *buffer)
Detailed Description
Prototypes and structures for the ring buffer module.
Definition in file ringbuffer.h.
Define Documentation
#define RING_BUFFER_MASK (RING_BUFFER_SIZE-1)
Used as a modulo operator as a % b = (a & (b − 1)) where a is a positive index in the buffer and b is the (power of two) size of the buffer.
Definition at line 36 of file ringbuffer.h.
Referenced by ring_buffer_dequeue(), ring_buffer_is_full(), ring_buffer_num_items(), ring_buffer_peek(), and ring_buffer_queue().
#define RING_BUFFER_SIZE 128
The size of a ring buffer. Due to the design only RING_BUFFER_SIZE-1 items can be contained in the buffer. The buffer size must be a power of two.
Definition at line 17 of file ringbuffer.h.
Typedef Documentation
typedef uint8_t ring_buffer_size_t
The type which is used to hold the size and the indicies of the buffer. Must be able to fit RING_BUFFER_SIZE .
Definition at line 28 of file ringbuffer.h.
typedef struct ring_buffer_t ring_buffer_t
Simplifies the use of struct ring_buffer_t.
Definition at line 41 of file ringbuffer.h.
Function Documentation
uint8_t ring_buffer_dequeue (ring_buffer_t * buffer, char * data)
Returns the oldest byte in a ring buffer.
Parameters:
buffer The buffer from which the data should be returned.
data A pointer to the location at which the data should be placed.
Returns:
1 if data was returned; 0 otherwise.
Definition at line 34 of file ringbuffer.c.
References ring_buffer_t::buffer, ring_buffer_is_empty(), RING_BUFFER_MASK, and ring_buffer_t::tail_index.
Referenced by ring_buffer_dequeue_arr().
uint8_t ring_buffer_dequeue_arr (ring_buffer_t * buffer, char * data, ring_buffer_size_t len)
Returns the len oldest bytes in a ring buffer.
Parameters:
buffer The buffer from which the data should be returned.
data A pointer to the array at which the data should be placed.
len The maximum number of bytes to return.
Returns:
The number of bytes returned.
Definition at line 45 of file ringbuffer.c.
References ring_buffer_dequeue(), and ring_buffer_is_empty().
void ring_buffer_init (ring_buffer_t * buffer)
Initializes the ring buffer pointed to by buffer. This function can also be used to empty/reset the buffer.
Parameters:
buffer The ring buffer to initialize.
Definition at line 8 of file ringbuffer.c.
References ring_buffer_t::head_index, and ring_buffer_t::tail_index.
uint8_t ring_buffer_is_empty (ring_buffer_t * buffer) [inline]
Returns whether a ring buffer is empty.
Parameters:
buffer The buffer for which it should be returned whether it is empty.
Returns:
1 if empty; 0 otherwise.
Definition at line 110 of file ringbuffer.h.
References ring_buffer_t::head_index, and ring_buffer_t::tail_index.
Referenced by ring_buffer_dequeue(), and ring_buffer_dequeue_arr().
uint8_t ring_buffer_is_full (ring_buffer_t * buffer) [inline]
Returns the number of items in a ring buffer.
Parameters:
buffer The buffer for which the number of items should be returned.
Returns:
The number of items in the ring buffer.
Definition at line 119 of file ringbuffer.h.
References ring_buffer_t::head_index, RING_BUFFER_MASK, and ring_buffer_t::tail_index.
Referenced by ring_buffer_queue().
ring_buffer_size_t ring_buffer_num_items (ring_buffer_t * buffer) [inline]
Returns whether a ring buffer is full.
Parameters:
buffer The buffer for which it should be returned whether it is full.
Returns:
1 if full; 0 otherwise.
Definition at line 128 of file ringbuffer.h.
References ring_buffer_t::head_index, RING_BUFFER_MASK, and ring_buffer_t::tail_index.
Referenced by ring_buffer_peek().
uint8_t ring_buffer_peek (ring_buffer_t * buffer, char * data, ring_buffer_size_t index)
Peeks a ring buffer, i.e. returns an element without removing it.
Parameters:
buffer The buffer from which the data should be returned.
data A pointer to the location at which the data should be placed.
index The index to peek.
Returns:
1 if data was returned; 0 otherwise.
Definition at line 60 of file ringbuffer.c.
References ring_buffer_t::buffer, RING_BUFFER_MASK, ring_buffer_num_items(), and ring_buffer_t::tail_index.
void ring_buffer_queue (ring_buffer_t * buffer, char data)
Adds a byte to a ring buffer.
Parameters:
buffer The buffer in which the data should be placed.
data The byte to place.
Definition at line 13 of file ringbuffer.c.
References ring_buffer_t::buffer, ring_buffer_t::head_index, ring_buffer_is_full(), RING_BUFFER_MASK, and ring_buffer_t::tail_index.
Referenced by ring_buffer_queue_arr().
void ring_buffer_queue_arr (ring_buffer_t * buffer, const char * data, ring_buffer_size_t size)
Adds an array of bytes to a ring buffer.
Parameters:
buffer The buffer in which the data should be placed.
data A pointer to the array of bytes to place in the queue.
size The size of the array.
Definition at line 26 of file ringbuffer.c.
References ring_buffer_queue().